# Generated by Django 4.2.4 on 2024-03-02 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=122)),
                ('lname', models.CharField(max_length=122)),
                ('profile_image', models.ImageField(blank=True, default=None, max_length=122, upload_to='upload/')),
                ('username', models.CharField(max_length=122)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=122)),
                ('userType', models.BooleanField()),
                ('address', models.CharField(max_length=122)),
                ('city', models.CharField(max_length=122)),
                ('state', models.CharField(max_length=122)),
                ('pincode', models.IntegerField(max_length=122)),
            ],
        ),
    ]
