# Generated by Django 4.2.4 on 2024-03-03 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docterpatientapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.TextField(),
        ),
    ]
